### ISSUE TITLE
Fix two scrollbars

### ISSUE THREAD

**Issue by paulormm** [mezuro/mezuro.github.io#5]
We have two scrollbars. I just need one.

**Comment by freemanpivo** [comment]
@paulormm , can you describe how I can find these scrollbars? I've visited mezuro.github.io, on Google Chrome and Firefox and the problem did not appear. I've considered too the difference between displays resolutions.

**Comment by paulormm** [comment]
Don't worry. Using Firefox and Chromium, It's fine. The problem just is with Chrome (on my Debian 8).

I think we can cancel this issue.

![screenshot from 2017-04-18 16 50 00](https://cloud.githubusercontent.com/assets/57861/25150329/f4af5ba0-2457-11e7-97a8-5ac4a7ea09ad.png)

**Comment by freemanpivo** [comment]
Fine! We've (me and @vitorbaraujo) found another problem. Visit [mezuro.github.io/tutorials] and note that cards are overriding images (On Chrome), and the size of these cards are not standardized.

**Comment by freemanpivo** [comment]
![screenshot from 2017-04-18 14-13-30](https://cloud.githubusercontent.com/assets/7088599/25151062/865c28ba-245a-11e7-811f-2979c2a20c00.png)
