### ISSUE TITLE
Share button does not appear on top of cards with white images

### ISSUE THREAD

**Issue by vitorbaraujo** [mezuro/mezuro.github.io#8]
Bug shown in image below
![image](https://cloud.githubusercontent.com/assets/12853199/25868827/7a8c1bb4-34d4-11e7-8f7f-dbfb8334e426.png)

**Comment by marceloabk** [comment]
I'm working with this issue

**Comment by paulormm** [comment]
Don't worry about this page. I think you guys can change the template to use a easier one.

**Comment by marceloabk** [comment]
Just finished this issue haha
<img width="1210" alt="captura de tela 2017-05-09 as 17 53 02" src="https://cloud.githubusercontent.com/assets/11621153/25872256/6239431e-34e0-11e7-9242-f378cebb523a.png">

But I can create another issue to change the current github.io template

**Comment by paulormm** [comment]
If it's Ok, that's fine! Don't worry about this page. Work on Mezuro as well ;)
